[project]
name = "vuln-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marko>=2.1.4",
    "pygithub>=2.6.1",
]
