name: Opengrep SAST Scan

# This workflow is triggered on pull requests to the main branch.
on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read # to check out private repos
  pull-requests: write # to comment on pull requests

jobs:
  opengrep:
    name: Opengrep SAST Scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} # The PR's branch
          fetch-depth: 0

      - name: Setup Opengrep
        run: |
          curl -fsSL https://raw.githubusercontent.com/opengrep/opengrep/main/install.sh | bash
          echo "/home/runner/.opengrep/cli/latest" >> $GITHUB_PATH

      - name: Run Opengrep
        id: opengrep-pr
        run: |
          opengrep ci --taint-intrafile
